### ISSUE TITLE
A Frp Server Config for Testing

### ISSUE THREAD

**Issue by shaowenchen** [shaowenchen/debugger-action#3]
You Server IP      : 139.198.113.238
Bind port          : 5443
token              : jqhVb79zYjxZWGtw

This is an example:

```yaml
name: kind
on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Creating kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
      - uses: shaowenchen/debugger-action@v1
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: 139.198.113.238
          frp_server_port: 5443
          frp_token: jqhVb79zYjxZWGtw
          ssh_port: 31000
 ```

Please use a port above 31000 for testing, if you use a certain port, please reply with the number
